version: "3"
services:
  s3:
    image: minio/minio
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
  app:
    image: dremio/dremio-oss:19.0
    ports:
    - "9047:9047"
    - "31010:31010"
  psotgres:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=dalong"